name: semibin_test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}
      run : |
        pip install pandas
        pip install numpy
        pip install .
        pip install pytest
        pip install hypothesis
        pip install python-igraph
        pip install torch
        pip install scikit-learn
        pip install requests
        pip install numexpr
        conda install -c bioconda bedtools hmmer fraggenescan==1.30 samtools
        conda install -c bioconda prodigal
        conda install -c conda-forge -c bioconda mmseqs2=13.45111
        python ./setup.py install
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        python -m pytest ./test
    - name: Test with SemiBin command
      shell: bash -l {0}
      run: |
        for t in integration-tests/*.py; do
          echo "Running $t ..."
          python $t
        done

