name: semibin_test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        numpy-version:
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
        exclude:
            # 3.7 is too old for NumPy 1.22+
            - python-version: '3.7'
              numpy-version: '1.22'
            - python-version: '3.7'
              numpy-version: '1.23'
            - python-version: '3.7'
              numpy-version: '1.24'

            # NumPy 1.19 is not available on 3.7-9
            - python-version: '3.7'
              numpy-version: '1.19'
            - python-version: '3.8'
              numpy-version: '1.19'
            - python-version: '3.9'
              numpy-version: '1.19'

            # NumPy 1.18 are too old for Python 3.9
            - python-version: '3.9'
              numpy-version: '1.18'

            # NumPy <1.21 are too old for Python 3.10
            - python-version: '3.10'
              numpy-version: '1.18'
            - python-version: '3.10'
              numpy-version: '1.19'
            - python-version: '3.10'
              numpy-version: '1.20'


            # NumPy <1.23 are too old for Python 3.11
            - python-version: '3.11'
              numpy-version: '1.18'
            - python-version: '3.11'
              numpy-version: '1.19'
            - python-version: '3.11'
              numpy-version: '1.20'
            - python-version: '3.11'
              numpy-version: '1.21'
            - python-version: '3.11'
              numpy-version: '1.22'

    steps:
    - uses: actions/checkout@v2
    - uses: mamba-org/setup-micromamba@v1
      with:
        cache-environment: true
        cache-downloads: false
        environment-name: semibin_test_env
        create-args: python=${{ matrix.python-version }} numpy=${{ matrix.numpy-version }}
    - name: Install dependencies
      shell: bash -l {0}
      run : |
        pip install pandas
        pip install numpy
        pip install .
        pip install pytest
        pip install hypothesis
        pip install python-igraph
        pip install torch
        pip install scikit-learn
        pip install requests
        pip install numexpr
        mamba install -c bioconda bedtools hmmer fraggenescan samtools==1.6
        mamba install -c bioconda prodigal
        mamba install -c conda-forge -c bioconda mmseqs2=13.45111
        python ./setup.py install
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        python -m pytest ./test
    - name: Test with SemiBin command
      shell: bash -l {0}
      run: |
        for t in integration-tests/*.py; do
          echo "Running $t ..."
          python $t
        done

